server:
  port: 5008

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_ancillary_service
    username: root
    password: Rishi@18

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true