server:
  port: 5009

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_booking_service
    username: root
    password: Rishi@18

  kafka:
    bootstrap-servers: localhost:9092

    # १. प्रोड्युसर ब्लॉक (मेसेज पाठवण्यासाठी)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # २. कडक बदल: कंझ्युमर ब्लॉक परत जोडला (ज्यामुळे 'kafkaConsumerConfig' शांत होईल)
    consumer:
      group-id: booking-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.rishi.event"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true