server:
  port: 5006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat_service
    username: root
    password: Rishi@18


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true