server:
  port: 5001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_service
    username: root
    password: Rishi@18

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true